Refactored the project
metakgp/mfqp pull request #21
Opened 2017-03-11 12:29 UTC by ayuhsya

- Moved all images to `/resources`
- Moved all scripts to `/scripts`
- Moved all data to `/data`
- `fuse.min.js` now loads from CDN instead of local storage

2017-03-11 12:44 UTC, athityakumar requested changes
Hey @ayuhsya ! Thanks for opening this PR! :smile: 

Have a look at the changes suggested. Also, typically, the sitemap looks like this - 

```
resources/
     images/
     js/ or scripts/
     css/ or styles/
```

Change the html files accordingly, to fit this the above sitemap.

2017-03-11 12:44 UTC, athityakumar commented on add_node.rb
> +obj = JSON.parse(File.read("./data/data.json"))
Just `obj = JSON.parse(File.read("data/data.json"))` will do.

2017-03-11 12:44 UTC, athityakumar commented on add_node.rb
> +  File.delete("./data/data.json")
Just `File.delete("data/data.json")` will do.

2017-03-11 12:44 UTC, athityakumar commented on add_node.rb
> +    File.open("./data/data.json", "w") { |file| file.write(JSON.pretty_generate(obj)) }
Same issue as above comment.

2017-03-11 12:44 UTC, athityakumar commented on add_node.rb
> +    File.open("./data/data.json", "w") { |file| file.write(JSON.generate(obj)) }
Same issue as above comment.

2017-03-11 13:05 UTC, athityakumar commented
@ayuhsya - No need to move the `data/` folder into `resources/`. Just make this change, and I'll merge it, if no other changes are required.

2017-03-11 13:16 UTC, athityakumar commented on index.html
> +        <script src="./resources/scripts/string_score.min.js"></script>
Change all the `./resources/` in this file to `resources/`. And we're good to go. :+1:

2017-03-11 13:17 UTC, athityakumar commented on index.html
> +             $.getJSON("./data/data.json")
Change this to `$.getJSON("data/data.json")`

2017-03-11 13:28 UTC, athityakumar commented on resources/scripts/worker.js
> -importScripts('fuse.min.js');
I don't think that the `new Fuse()` function in this file will work without import `fuse.min.js` file. We do need it.

2017-03-11 13:31 UTC, ayuhsya commented on resources/scripts/worker.js
> -importScripts('fuse.min.js');
@athityakumar How can I test it?

2017-03-11 13:43 UTC, athityakumar commented on resources/scripts/worker.js
> -importScripts('fuse.min.js');
For usual JS testing, you can check out the `Console` on your browser (Inspect > Console option appears). However, testing for worker js files would have to be done on server - you can push to your fork, publish that branch in your fork as a `gh-pages` website. Then, have a look at ayuhsya.github.io/mfqp/ and check the Console of that website.

2017-03-11 13:47 UTC, amrav commented
Hmm, why can't you test js workers in the browser locally?

On Sat, 11 Mar 2017 at 13:43, Athitya Kumar <notifications@github.com>
wrote:

> *@athityakumar* commented on this pull request.
> ------------------------------
>
> In resources/scripts/worker.js
> <https://github.com/metakgp/mfqp/pull/21#discussion_r105533519>:
>
> > @@ -1,5 +1,3 @@
> -importScripts('fuse.min.js');
>
> For usual JS testing, you can check out the Console on your browser
> (Inspect > Console option appears). However, testing for worker js files
> would have to be done on server - you can push to your fork, publish that
> branch in your fork as a gh-pages website. Then, have a look at
> ayuhsya.github.io/mfqp/ and check the Console of that website.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/metakgp/mfqp/pull/21#discussion_r105533519>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABIZ_yrXeB2h5QB8gq1tKXt4tpuzi1qoks5rkqTsgaJpZM4MaMOL>
> .
>

2017-03-11 18:10 UTC, athityakumar commented on resources/scripts/worker.js
> -importScripts('fuse.min.js');
@ayuhsya - Or you can just restore the `fuse.min.js` file back, and I'll merge this. Maybe we can work on loading `fuse.min.js` on another PR. :smile:

2017-03-11 19:14 UTC, icyflame commented
@athityakumar @ayuhsya I think you guys don't know about `SimpleHTTPServer` :slightly_smiling_face: 

You can test everything (including JavaScript) by running: 

`$ python -m SimpleHTTPServer` 

from the `mfqp/` directory and then visiting `localhost:8000` on your browser.

@amrav This should fix their problem.

2017-03-11 20:22 UTC, ayuhsya commented
@icyflame I was using `SimpleHTTPServer` itself to test the HTML all this while, there's some Apache thing to create local server too, but I find it inconvenient to use. 

I just can't find any usage of the file `worker.js` in the project that's why I asked how to test it. I'll just restore the `fuse` script for this PR.

2017-03-11 20:55 UTC, athityakumar approved these changes

2017-03-11 21:00 UTC, merged

2017-03-11 22:11 UTC, amrav commented
You can also use node's http-server, which is async and gives slightly
nicer output IMO. (npm install -g http-server)

I think worker.js is unused. This whole thing was hacked together in a
night or two, so code quality went out of the window - please
reactor/rewrite liberally :)

On Sat, 11 Mar 2017 at 20:22, Ayushya Anand <notifications@github.com>
wrote:

> @icyflame <https://github.com/icyflame> I was using SimpleHTTPServer
> itself to test the HTML all this while, there's some Apache thing to create
> local server too, but I find it inconvenient to use.
>
> I just can't find any usage of the file worker.js in the project that's
> why I asked how to test it. I'll just restore the fuse script for this PR.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/metakgp/mfqp/pull/21#issuecomment-285897297>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABIZ_7ihYRwTvan4kxuK02aqc9_sLIieks5rkwKUgaJpZM4MaMOL>
> .
>

2017-03-12 21:13 UTC, icyflame commented
@athityakumar refactor looks good. repo looks pretty now. Thanks! :smile: