Add ability to pre-fill the search bar from URL param
metakgp/mfqp pull request #30
Opened 2017-04-07 07:08 UTC by icyflame

This will enable the addition of MFQP as a custom search engine in Chrome. (with a URL structure something like: `https://qp.metakgp.org/?search=%s`

I have tested this change, and it works well.

2017-04-07 07:46 UTC, athityakumar requested changes
A minor change required. 

Irrespective of the query in the url param, a `/` gets added at last - which messes up the search results at times.

Search as URL param : 
![image](https://cloud.githubusercontent.com/assets/17109060/24790150/a04f970e-1b93-11e7-966b-c0872e1891b3.png)

Search as input to search bar :
![image](https://cloud.githubusercontent.com/assets/17109060/24790178/c918518a-1b93-11e7-8d8e-34d43933cec2.png)

Notice the 2nd result missing in case 1. Maybe just the `/` can be removed from the `search_query` variable in [line 107](https://github.com/icyflame/mfqp/blob/add-search-url-param/index.html#L107)?

2017-04-07 18:01 UTC, athityakumar commented
@icyflame - I have sent a [PR](https://github.com/icyflame/mfqp/pull/1) for the same. Have a look! :smile:

2017-04-07 18:13 UTC, icyflame commented
![image](https://cloud.githubusercontent.com/assets/3668034/24813432/99168f4e-1beb-11e7-8ec2-7ad181717501.png)

I added that search engine to Chrome 56. Then, I searched using the address bar. There was no `/` that was appended.

> Irrespective of the query in the url param, a / gets added at last - which messes up the search results at times.

Who adds the `/`? If the user manually adds it, that's something that they have chosen to. I don't see the browser adding anything by default even when I manually type out the URL.

2017-04-07 18:23 UTC, athityakumar commented
It gets added by the browser itself (I think. Can't think of any other reason), after the user has typed his search param and pressed the Enter button. For example,

Search param :
![image](https://cloud.githubusercontent.com/assets/17109060/24813832/38f789ea-1bed-11e7-906c-9f382dc12346.png)

Result URL shows a `/` at the end :
![image](https://cloud.githubusercontent.com/assets/17109060/24813841/4455768a-1bed-11e7-910c-fc23b6ca4d1f.png)

I've added it as a search engine to Google Chrome Version 56.0.2924.87 (64-bit).

2017-04-07 18:26 UTC, icyflame commented
@athityakumar Can you post the search engine entry here? You might have put a `/` after the `%s`. If you add the search engine URL as `http://localhost:8000/?search=%s` the `/` won't be appended.

In any case, it will be a good idea to remove trailing forward slashes. So, you should change your PR on the other issue to ensure that the last character is a forward slash before slicing it away. :smile:

2017-04-07 18:29 UTC, athityakumar commented
![image](https://cloud.githubusercontent.com/assets/17109060/24814120/12d05c5a-1bee-11e7-89f3-a596df71dd8a.png)

Sure, I'll do the required changes on that PR. :smile:

2017-04-07 18:29 UTC, icyflame commented
@athityakumar Actually, I want to look at the URL that you added in the search engine. That has been wrapped out of the frame.

2017-04-07 18:31 UTC, athityakumar commented
@icyflame - Um, isn't it the `http://localhost:8000/?search=%s`?

2017-04-07 18:48 UTC, icyflame commented
Hmm, okay, I guess your browser decided to append the `/` to the query. Mine doesn't. Weirdly enough, I am on the **exact same build of Chrome**: Version 56.0.2924.87 (64-bit)

Okay, I will merge that PR and that should update the commit here.

2017-04-07 19:06 UTC, athityakumar commented
Weird o weird. :confused: 

I've updated the other PR. :smile:

2017-04-08 06:36 UTC, icyflame commented
@athityakumar Merged. I have tested with multiple trailing forward slashes, works fine.

2017-04-08 06:36 UTC, athityakumar approved these changes

2017-04-08 07:07 UTC, athityakumar commented
@icyflame - No more issues from my side, I've approved the PR. Let's wait for reviews of @vivekiitkgp & @amrav before merging this in. :smile:

2017-04-14 05:16 UTC, icyflame commented
@vivekiitkgp and @amrav Please review this PR. :slightly_smiling_face:

I will merge this PR in a few hours. Thanks!

2017-04-14 05:34 UTC, raivivek approved these changes

2017-04-15 13:10 UTC, merged